### ISSUE TITLE
PostCSS for external stylesheets

### ISSUE THREAD

**Issue by mattkingshott** [beyondcode/tailwindcss-jit-cdn#1]
This is a fantastic package and I'm really eager to use it!

One thing holds me back, and that's the fact that I've used `@apply` in external stylesheets. Do you think this is something that you can add to the library?

Thanks!

**Comment by mpociot** [comment]
So you would like to do something like this:

```
<link rel="stylesheet" href="/css/app.css">
```

And within your `app.css` file have `@apply` / PostCSS?

I'm not sure if that's doable without making additional XHR requests to fetch the CSS - and even then it would only work when the CSS is not on another (sub)domain because of CSRF issues.

I was hoping that you could just access the style using `document.styleSheets`, but the browser tries to be clever about it and strips out any invalid CSS rules.

For example this:

```
<style>
	.foo {
		@apply bar;
	}
<style>	
```

When accessed using `document.styleSheets` returns:

![image](https://user-images.githubusercontent.com/804684/118994305-800ca280-b986-11eb-9155-90ac498c16aa.png)

**Comment by mattkingshott** [comment]
Ah, that's a shame... but I guess making multiple XHR requests is not a good solution, particularly in production.
